### PR TITLE
Add missing LICENSE file and license information in package.json

### LINKED ISSUE #19: Missing license information on npm
While the readme states that this project uses the MIT license, the npm package shows as "License: none" on https://www.npmjs.com/package/component-event/v/0.1.4.

This prevents the package being mirrored to Maven using WebJars and breaks the dependency tree for one of our projects.

Could you possibly add the license information for this package on npm? In particular we would need it on version 0.1.4.

Thanks in advance!

### PR DESCRIPTION
**Pull request by jfastnacht**
Fixes #19

### CODE REVIEW

**Comment by jfastnacht** [comment]
@TooTallNate sorry for the disturbance, but you were the last one active here. Would you be so kind to have a look at this and merge it (and release a new version)? The package is part of a set of dependencies and no "official" WebJar can be created due to the missing license. Thanks!

**Comment by jfastnacht** [comment]
Is there anyone in this organization who feels responsible for this? I'm stuck, so sorry for the disturbance, I had a look into your activity feeds and you're in the organization and were active within the last few weeks:

@rauchg @blakeembrey @cristiandouce @dominicbarnes @dy @lancejpollard @pirxpilot @retrofox @dandv @matthewmueller @stagas @travisjeffery @vendethiel @wryk

**Review by stagas — APPROVED** [review]

**Comment by jfastnacht** [comment]
@stagas thank you for approving the change. Can you merge it / release the new version?

**Comment by stagas** [comment]
Done @jfastnacht https://www.npmjs.com/package/component-event/v/0.2.1

**Pull request merged**
